version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
          - conf.env
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  
  go:
    container_name: go
    build:
      context: .
    depends_on:
      - "postgres"
    ports:
      - "8000:8000"
volumes:
  dbdata: 
